baseurl = "https://badtothecode.netlify.com/"
languageCode = "en"
title = "bad to the code"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/madcap1090\">William Bourgeois</a> 2020"
disqusShortname = "bad-to-the-code"
googleAnalytics = "UA-137981534-1"
Paginate = 5 # Number of posts per page
enableRobotsTXT = true
enableEmoji = true

# Logo image. This is displayed ogp image.
#  logo = "/path/to/logo"
favicon = "/static"


[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "William Bourgeois" # Author full name
authorEmail = "madcap1090@gmail.com" # Author email

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article

[params.features]
disqusOnDemand = true  # Load Disqus comments on click


[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
twitter = "WilliamBourgeoi"
github = "madcap1090"
email = "madcap1090@gmail.com"
linkedin = "williambourgeois"
#facebook = "ramon.marquez.967/videos/1878191778880532/"
facebook = "OClassicoOficial/videos/391802167961744/"
instagram = ""
codepen = ""
rss = "index.xml" # Add this to show RSS button in social.

[params.social.config]
platforms = ["facebook","instagram","email","codepen","linkedin","twitter","github"]

[params.matomoAnalytics]
siteID = 1
rootURL = "//matomo.example.com/"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

[ignorefiles]
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

