<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"  lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1"/>

<title>Belgian parliamentarians Twitter accounts | bad to the code</title>

<meta property='og:title' content='Belgian parliamentarians Twitter accounts - bad to the code'>
<meta property='og:description' content='Now that we can scrape the names of the parliamentarians of the 54th legislature, we can try to find their Twitter accounts too.
Let’s start by reconstructing the list. Then we can search Twitter for their accounts handles. A bit of grunt work and no visuals in this post, but it is needed to harvest parlaimentarians’ tweets soonish.
Starting with attaching libraries, and in particular ‘rtweet’.
#librarieslibrary(&quot;tidyverse&quot;)library(&quot;rvest&quot;)library(&quot;glue&quot;)library(&quot;rtweet&quot;)library(&quot;purrr&quot;)# the ones seating currently, with their (current) partyurl &lt;- paste0(&quot;http://www.'>
<meta property='og:url' content='/post/belgian-parliamentarians-twitter-accounts/'>
<meta property='og:site_name' content='bad to the code'>
<meta property='og:type' content='article'><meta property='og:image' content='https://www.gravatar.com/avatar/5f460ebf37e30791f47bb5be3de73e3a?s=256'><meta property='article:author' content='https://facebook.com/OClassicoOficial/videos/391802167961744/'><meta property='article:section' content='Post'><meta property='article:tag' content='Belgian politics'><meta property='article:tag' content='Twitter'><meta property='article:published_time' content='2019-05-02T00:00:00Z'/><meta property='article:modified_time' content='2019-05-02T00:00:00Z'/><meta name='twitter:card' content='summary'><meta name='twitter:site' content='@WilliamBourgeoi'><meta name='twitter:creator' content='@WilliamBourgeoi'>


<link href="/index.xml" rel="alternate" type="application/rss+xml" title="bad to the code" />

<link rel="stylesheet" href="/css/style.css"/><link rel='stylesheet' href='/css/custom.css'><link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
</head>
<body>
<section class="section">
  <div class="container">
    <nav class="nav">
      <div class="nav-left">
        <a class="nav-item" href="/">
          <h1 class="title is-4">bad to the code</h1>
        </a>
      </div>
      <div class="nav-right">
        <nav class="nav-item level is-mobile"><a class="level-item" aria-label="facebook" href='https://facebook.com/OClassicoOficial/videos/391802167961744/'
            target='_blank' rel='noopener'>
            <span class="icon">
              <i class><svg viewbox='0 0 24 24' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' aria-hidden='true'>
    
    <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"/>
    
  </svg></i>
            </span>
          </a><a class="level-item" aria-label="email" href='mailto:madcap1090@gmail.com'
            target='_blank' rel='noopener'>
            <span class="icon">
              <i class><svg viewbox='0 0 24 24' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' aria-hidden='true'>
    
    <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/>
    <polyline points="22,6 12,13 2,6"/>
    
  </svg></i>
            </span>
          </a><a class="level-item" aria-label="linkedin" href='https://linkedin.com/in/williambourgeois'
            target='_blank' rel='noopener'>
            <span class="icon">
              <i class><svg viewbox='0 0 24 24' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' aria-hidden='true'>
    
    <path stroke-width="1.8" d="m5.839218,4.101561c0,1.211972 -0.974141,2.194011 -2.176459,2.194011s-2.176459,-0.982039 -2.176459,-2.194011c0,-1.211094 0.974141,-2.194011 2.176459,-2.194011s2.176459,0.982917 2.176459,2.194011zm0.017552,3.94922l-4.388022,0l0,14.04167l4.388022,0l0,-14.04167zm7.005038,0l-4.359939,0l0,14.04167l4.360816,0l0,-7.370999c0,-4.098413 5.291077,-4.433657 5.291077,0l0,7.370999l4.377491,0l0,-8.89101c0,-6.915523 -7.829986,-6.66365 -9.669445,-3.259423l0,-1.891237z"/>
    
  </svg></i>
            </span>
          </a><a class="level-item" aria-label="twitter" href='https://twitter.com/WilliamBourgeoi'
            target='_blank' rel='noopener'>
            <span class="icon">
              <i class><svg viewbox='0 0 24 24' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' aria-hidden='true'>
    
    <path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"/>
    
  </svg></i>
            </span>
          </a><a class="level-item" aria-label="github" href='https://github.com/madcap1090'
            target='_blank' rel='noopener'>
            <span class="icon">
              <i class><svg viewbox='0 0 24 24' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' aria-hidden='true'>
    
    <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"/>
    
  </svg></i>
            </span>
          </a></nav>
      </div>
    </nav>

    <nav class="nav">
      

      
    </nav>

  </div>
</section>
<section class="section">
  <div class="container">
    <div class="subtitle tags is-6 is-pulled-right">
      
      
<a class="subtitle is-6" href="/tags/belgian-politics">#Belgian politics</a>



  
  | <a class="subtitle is-6" href="/tags/twitter">#Twitter</a>
  

      
    </div>
    <h2 class="subtitle is-6">May 2, 2019</h2>
    <h1 class="title">Belgian parliamentarians Twitter accounts</h1>
    
    <div class="content">
      


<p>Now that we can scrape the names of the parliamentarians of the 54th legislature, we can try to find their Twitter accounts too.</p>
<p>Let’s start by reconstructing the list. Then we can search Twitter for their accounts handles. A bit of grunt work and no visuals in this post, but it is needed to harvest parlaimentarians’ tweets soonish.</p>
<p>Starting with attaching libraries, and in particular <a href="https://rtweet.info/">‘rtweet’</a>.</p>
<pre class="r"><code>#libraries
library(&quot;tidyverse&quot;)
library(&quot;rvest&quot;)
library(&quot;glue&quot;)
library(&quot;rtweet&quot;)
library(&quot;purrr&quot;)

# the ones seating currently, with their (current) party

url &lt;- paste0(&quot;http://www.dekamer.be/kvvcr/showpage.cfm?section=&quot;,
              &quot;/depute&amp;language=nl&amp;cfm=/site/wwwcfm/depute/cvlist54.cfm&quot;)

table &lt;- url %&gt;% 
  read_html() %&gt;% 
  html_nodes(&quot;#story &gt; table&quot;) %&gt;% 
  html_table()

table &lt;- table[[1]]

names(table) &lt;- c(&quot;ln_fn&quot;, &quot;party&quot;, &quot;d1&quot;, &quot;d2&quot;) # ln_fn is last name, first name
table &lt;- table %&gt;% 
  select(ln_fn, party)

table &lt;- table %&gt;%
  mutate(ln_fn = str_replace_all(ln_fn,&quot;  +&quot;,&quot; &quot;))

# the ones that have left (without party)

url &lt;- paste0(&quot;https://www.dekamer.be/kvvcr/showpage.cfm?section&quot;,
              &quot;=/depute&amp;language=nl&amp;cfm=cvlist54.cfm?legis=54&amp;today=n&quot;)

table_54 &lt;- url %&gt;% 
  read_html() %&gt;% 
  html_nodes(&quot;#story &gt; table&quot;) %&gt;% 
  html_table()

table_54 &lt;- table_54[[1]] # extracting the dataframe

names(table_54) &lt;- c(&quot;ln_fn&quot;, &quot;d1&quot;, &quot;d2&quot;, &quot;d3&quot;)  
table_54 &lt;- table_54 %&gt;% 
  select(ln_fn) %&gt;% 
  arrange(ln_fn)

table_54 &lt;- table_54 %&gt;%
  mutate(ln_fn = str_replace_all(ln_fn,&quot;  +&quot;,&quot; &quot;))

old_members &lt;- table_54 %&gt;% 
  anti_join(table) %&gt;% 
  mutate(party = &quot;tbd&quot;)

table &lt;- rbind(table, old_members)

saveRDS(table, &quot;./data/20190502/table.rds&quot;)

rm(old_members)
rm(table_54)
rm(url)</code></pre>
<p>How many do we have?</p>
<pre class="r"><code>nrow(table)</code></pre>
<pre><code>## [1] 179</code></pre>
<p>Ok, did not lose any along the way. Now we have a data frame with the last name and first name of the 179 persons who seated in the 54th legislature (by now there will be few or no changes, since we are so close to this month’s elections).</p>
<p>Next the twitter API credentials are needed to use the rtweet package. Documentation can be found <a href="https://rtweet.info/#api-authorization">here</a></p>
<p>Once authenticated, based on our parliamentarian’s name and using the ‘search_users’ function we can find their twitter accounts. I had some success using a for loop in the past, but will try to use the purrr package this time around.</p>
<pre class="r"><code># so tweak the function, because it tries to find by default 100 users
# and because we want to keep track of who we searched for in the results
# take only first result for now

search &lt;- function(x){print (x)
  search_users(x, n=1) %&gt;% # only return one line per name
    mutate(ln_fn = x)} # keep track of who we searched for</code></pre>
<p>Using the function ‘possibly’ a data frame can be created without stopping or including errors.</p>
<pre class="r"><code>twitter_users &lt;- map_df(table$ln_fn,possibly(.f= search, otherwise = NULL))</code></pre>
<p>The nice thing about it is that a lot of information can be collected using the Twitter API. Have look yourself:</p>
<pre class="r"><code>names(twitter_users)</code></pre>
<pre><code>##  [1] &quot;user_id&quot;                 &quot;status_id&quot;              
##  [3] &quot;created_at&quot;              &quot;screen_name&quot;            
##  [5] &quot;text&quot;                    &quot;source&quot;                 
##  [7] &quot;display_text_width&quot;      &quot;reply_to_status_id&quot;     
##  [9] &quot;reply_to_user_id&quot;        &quot;reply_to_screen_name&quot;   
## [11] &quot;is_quote&quot;                &quot;is_retweet&quot;             
## [13] &quot;favorite_count&quot;          &quot;retweet_count&quot;          
## [15] &quot;hashtags&quot;                &quot;symbols&quot;                
## [17] &quot;urls_url&quot;                &quot;urls_t.co&quot;              
## [19] &quot;urls_expanded_url&quot;       &quot;media_url&quot;              
## [21] &quot;media_t.co&quot;              &quot;media_expanded_url&quot;     
## [23] &quot;media_type&quot;              &quot;ext_media_url&quot;          
## [25] &quot;ext_media_t.co&quot;          &quot;ext_media_expanded_url&quot; 
## [27] &quot;ext_media_type&quot;          &quot;mentions_user_id&quot;       
## [29] &quot;mentions_screen_name&quot;    &quot;lang&quot;                   
## [31] &quot;quoted_status_id&quot;        &quot;quoted_text&quot;            
## [33] &quot;quoted_created_at&quot;       &quot;quoted_source&quot;          
## [35] &quot;quoted_favorite_count&quot;   &quot;quoted_retweet_count&quot;   
## [37] &quot;quoted_user_id&quot;          &quot;quoted_screen_name&quot;     
## [39] &quot;quoted_name&quot;             &quot;quoted_followers_count&quot; 
## [41] &quot;quoted_friends_count&quot;    &quot;quoted_statuses_count&quot;  
## [43] &quot;quoted_location&quot;         &quot;quoted_description&quot;     
## [45] &quot;quoted_verified&quot;         &quot;retweet_status_id&quot;      
## [47] &quot;retweet_text&quot;            &quot;retweet_created_at&quot;     
## [49] &quot;retweet_source&quot;          &quot;retweet_favorite_count&quot; 
## [51] &quot;retweet_retweet_count&quot;   &quot;retweet_user_id&quot;        
## [53] &quot;retweet_screen_name&quot;     &quot;retweet_name&quot;           
## [55] &quot;retweet_followers_count&quot; &quot;retweet_friends_count&quot;  
## [57] &quot;retweet_statuses_count&quot;  &quot;retweet_location&quot;       
## [59] &quot;retweet_description&quot;     &quot;retweet_verified&quot;       
## [61] &quot;place_url&quot;               &quot;place_name&quot;             
## [63] &quot;place_full_name&quot;         &quot;place_type&quot;             
## [65] &quot;country&quot;                 &quot;country_code&quot;           
## [67] &quot;geo_coords&quot;              &quot;coords_coords&quot;          
## [69] &quot;bbox_coords&quot;             &quot;status_url&quot;             
## [71] &quot;name&quot;                    &quot;location&quot;               
## [73] &quot;description&quot;             &quot;url&quot;                    
## [75] &quot;protected&quot;               &quot;followers_count&quot;        
## [77] &quot;friends_count&quot;           &quot;listed_count&quot;           
## [79] &quot;statuses_count&quot;          &quot;favourites_count&quot;       
## [81] &quot;account_created_at&quot;      &quot;verified&quot;               
## [83] &quot;profile_url&quot;             &quot;profile_expanded_url&quot;   
## [85] &quot;account_lang&quot;            &quot;profile_banner_url&quot;     
## [87] &quot;profile_background_url&quot;  &quot;profile_image_url&quot;      
## [89] &quot;ln_fn&quot;</code></pre>
<p>Some of the fields, like “hashstags” contain lists.</p>
<p>Arranging columns:</p>
<pre class="r"><code>twitter_users &lt;- twitter_users %&gt;% 
  select(ln_fn, everything())</code></pre>
<p>These names return an error using the “twitter_user” function. But these politicians do not tweet. We can skip them.</p>
<pre class="r"><code>list_no_twitter &lt;- c(&quot;Detiège Maya&quot;, &quot;Mathot Alain&quot;, &quot;Pivin Philippe&quot;,
                     &quot;Wilrycx Frank&quot;)</code></pre>
<p>We now have a data frame with 152 users for our 175 politicians.</p>
<p>We need to find the right user ids or twitter handles, by looking at key fields in the data frame returned by the ‘search_user’ function. (summarised in a smaller data frame)</p>
<pre class="r"><code>inspect &lt;- twitter_users %&gt;%
  select(ln_fn, name, screen_name, description, text)</code></pre>
<p>Luckily most often the first result is the correct one. Although there are also sometimes surprises. At least these do not seem like descriptions of Belgian parliamentarians.</p>
<pre class="r"><code>descriptions &lt;- inspect %&gt;% 
  filter(ln_fn == &quot;Bracke Siegfried&quot; 
         | ln_fn == &quot;Fernandez Fernandez Julie&quot;
         | ln_fn == &quot;Top Alain&quot;
         | ln_fn == &quot;Bonte Hans&quot;) %&gt;% 
  select(description)

descriptions</code></pre>
<pre><code>## # A tibble: 4 x 1
##   description                                                              
##   &lt;chr&gt;                                                                    
## 1 Levensgenieter                                                           
## 2 Als er niet kan worden gelachen, is het niet ernstig. Links of rechts is~
## 3 Trusted HR advisor for all things BPO, technology, global payroll and sh~
## 4 Legacy Miami Top 40 Under 40 | HACCOF Top 20 Under 40 | Caribbean-born C~</code></pre>
<p>These seem obviously wrong.</p>
<pre class="r"><code>find_again &lt;- tibble(&quot;ln_fn&quot; = c(&quot;Bonte Hans&quot;,&quot;Ceysens Patricia&quot;,&quot;Chabot Jacques&quot;,
                                 &quot;Fernandez Fernandez Julie&quot;,&quot;Geerts David&quot;,
                                 &quot;Henry Olivier&quot;,&quot;Janssen Werner&quot;, &quot;Janssens Dirk&quot;,
                                 &quot;Matz Vanessa&quot;, &quot;Metsu Koen&quot;, &quot;Miller Richard&quot;,
                                 &quot;Pehlivan Fatma&quot;,&quot;Smeyers Sarah&quot;,&quot;Top Alain&quot;,
                                 &quot;Van de Velde Robert&quot;))</code></pre>
<p>Would they be first 10 of the search result?</p>
<pre class="r"><code>search &lt;- function(x){print (x)
  search_users(x, n=10) %&gt;% 
    mutate(ln_fn = x)} # keep track of who we searched for

twitter_users_2 &lt;- map_df(find_again$ln_fn,
                          possibly(.f= search, otherwise = NULL))</code></pre>
<pre><code>## [1] &quot;Bonte Hans&quot;
## [1] &quot;Ceysens Patricia&quot;
## [1] &quot;Chabot Jacques&quot;
## [1] &quot;Fernandez Fernandez Julie&quot;
## [1] &quot;Geerts David&quot;
## [1] &quot;Henry Olivier&quot;
## [1] &quot;Janssen Werner&quot;
## [1] &quot;Janssens Dirk&quot;
## [1] &quot;Matz Vanessa&quot;
## [1] &quot;Metsu Koen&quot;
## [1] &quot;Miller Richard&quot;
## [1] &quot;Pehlivan Fatma&quot;
## [1] &quot;Smeyers Sarah&quot;
## [1] &quot;Top Alain&quot;
## [1] &quot;Van de Velde Robert&quot;</code></pre>
<pre class="r"><code>inspect &lt;- twitter_users_2 %&gt;%
  select(ln_fn, name, screen_name, description, text)</code></pre>
<p>The new batch can easily be identified and added to the first batch.</p>
<pre class="r"><code>twitter_users &lt;- twitter_users %&gt;% 
  filter(!ln_fn %in% find_again$ln_fn) %&gt;% 
  rbind(twitter_users_2 %&gt;% 
  slice(13, 21, 30, 45, 51, 71, 76 , 99, 113))</code></pre>
<p>We are still missing these:</p>
<pre class="r"><code>setdiff(setdiff(table$ln_fn, twitter_users$ln_fn), list_no_twitter)</code></pre>
<pre><code>##  [1] &quot;Bonte Hans&quot;                &quot;Brotcorne Christian&quot;      
##  [3] &quot;Cassart-Mailleux Caroline&quot; &quot;Ceysens Patricia&quot;         
##  [5] &quot;Cheron Marcel&quot;             &quot;de Coster-Bauchau Sybille&quot;
##  [7] &quot;Delannois Paul-Olivier&quot;    &quot;Delpérée Francis&quot;         
##  [9] &quot;Devin Laurent&quot;             &quot;D&#39;Haese Christoph&quot;        
## [11] &quot;Dierick Leen&quot;              &quot;Frédéric André&quot;           
## [13] &quot;Galant Isabelle&quot;           &quot;Gerkens Muriel&quot;           
## [15] &quot;Goffinet Anne-Catherine&quot;   &quot;Gustin Luc&quot;               
## [17] &quot;Janssens Dirk&quot;             &quot;Marghem Marie-Christine&quot;  
## [19] &quot;Miller Richard&quot;            &quot;Muylle Nathalie&quot;          
## [21] &quot;Pehlivan Fatma&quot;            &quot;Pirlot Sébastian&quot;         
## [23] &quot;Vande Lanotte Johan&quot;       &quot;Van den Bergh Jef&quot;        
## [25] &quot;Van de Velde Robert&quot;       &quot;Van Quickenborne Vincent&quot; 
## [27] &quot;Van Rompuy Eric&quot;           &quot;Vanvelthoven Peter&quot;</code></pre>
<p>Some of these surely have a twitter account. More searching is needed to find:</p>
<p><span class="citation">@CarolineCassart</span>
<span class="citation">@patriciaceysens</span>
<span class="citation">@podelannois</span>
<span class="citation">@leendierick</span>
<span class="citation">@dirkjanssens19</span>
<span class="citation">@millerrichardmr</span>
<span class="citation">@nathaliemuylle</span>
<span class="citation">@jefvandenbergh</span>
<span class="citation">@VincentVQ</span>
<span class="citation">@VvelthovenPeter</span>
<span class="citation">@pehlivan_fatma</span>
<span class="citation">@FrankWilrycx</span>
<span class="citation">@McMarghem</span>
<span class="citation">@robvandevelde</span></p>
<pre class="r"><code>more &lt;- tibble(handle = wrapr::qc(CarolineCassart, patriciaceysens, podelannois,
                                  leendierick,dirkjanssens19, millerrichardmr,
                                  nathaliemuylle, jefvandenbergh, VincentVQ,
                                  VvelthovenPeter, pehlivan_fatma, FrankWilrycx,
                                  McMarghem),
               ln_fn = c(&quot;Cassart-Mailleux Caroline&quot;, &quot;Ceysens Patricia&quot;,
                         &quot;Delannois Paul-Olivier&quot;, &quot;Dierick Leen&quot;, 
                         &quot;Janssens Dirk&quot;, &quot;Miller Richard&quot;, &quot;Muylle Nathalie&quot;, 
                         &quot;Van den Bergh Jef&quot;, &quot;Van Quickenborne Vincent&quot;, 
                         &quot;Vanvelthoven Peter&quot;, &quot;Pehlivan Fatma&quot; , 
                         &quot;Wilrycx Frank&quot;, &quot;Marghem Marie-Christine&quot;))

more_1 &lt;- more %&gt;% 
  filter(handle !=&quot;pehlivan_fatma&quot;,
         handle !=&quot;FrankWilrycx&quot;)

more_2 &lt;- more %&gt;% 
  filter(handle ==&quot;pehlivan_fatma&quot; |
         handle ==&quot;FrankWilrycx&quot;)</code></pre>
<pre class="r"><code>search &lt;- function(x){print (x)
  search_users(x, n=1)} # keep track of who we searched for

twitter_users_3 &lt;- map_df(more_1$handle,possibly(.f= search, otherwise = NULL)) %&gt;% 
  cbind(more_1$ln_fn) %&gt;%
  rename(&quot;ln_fn&quot; = &quot;more_1$ln_fn&quot;) %&gt;% 
  select(ln_fn, everything())</code></pre>
<pre><code>## [1] &quot;CarolineCassart&quot;
## [1] &quot;patriciaceysens&quot;
## [1] &quot;podelannois&quot;
## [1] &quot;leendierick&quot;
## [1] &quot;dirkjanssens19&quot;
## [1] &quot;millerrichardmr&quot;
## [1] &quot;nathaliemuylle&quot;
## [1] &quot;jefvandenbergh&quot;
## [1] &quot;VincentVQ&quot;
## [1] &quot;VvelthovenPeter&quot;
## [1] &quot;McMarghem&quot;</code></pre>
<pre class="r"><code>twitter_users &lt;- rbind(twitter_users, twitter_users_3)

nrow(twitter_users)</code></pre>
<pre><code>## [1] 158</code></pre>
<p>Still problems with the last two. “FrankWilrycx” probably because he has not tweeted yet. And “pehlivan_fatma” was a bit harder to find</p>
<pre class="r"><code>more_2 &lt;- more %&gt;% 
  filter(handle ==&quot;pehlivan_fatma&quot;)

search &lt;- function(x){print (x)
  search_users(x, n=11)} # keep track of who we searched for

twitter_users_4 &lt;- map_df(more_2$handle,
                          possibly(.f= search, 
                                   otherwise = NULL)) %&gt;% 
  cbind(more_2$ln_fn) %&gt;%
  rename(&quot;ln_fn&quot; = &quot;more_2$ln_fn&quot;) %&gt;% 
  select(ln_fn, everything()) %&gt;% 
  slice(11)</code></pre>
<pre><code>## [1] &quot;pehlivan_fatma&quot;</code></pre>
<pre class="r"><code>twitter_users &lt;- rbind(twitter_users, twitter_users_4)

nrow(twitter_users)</code></pre>
<pre><code>## [1] 159</code></pre>
<p>There are 159 Twitter handles, out of 179 parliamentarians.</p>
<p>(if you want to have fun with the profile pics they are in <a href="https://twitter.com/%7Bhandle%7D/photo" class="uri">https://twitter.com/{handle}/photo</a>)</p>
<p>We are now ready to extract a considerable amount of their tweets.</p>
<pre class="r"><code>saveRDS(twitter_users, &quot;./data/20190502/twitter_users.rds&quot;)</code></pre>

      
      <div class="related">

<h3>Similar articles:</h3>
<ul>
	
	<li><a href="/post/members-of-the-chamber-of-representatives-of-belgium-54th-legistlature/">members of the chamber of representatives of Belgium, 54th legistlature</a></li>
	
</ul>
</div>
      
    </div>
    
  </div>
</section>


<section class="section">
  <div class="container">
    <aside><div id="disqus_thread"></div></aside>
  
    <div id="show_comments"><a id="load_comments" class="button is-link">Load comments</a></div>
  
    <script type="text/javascript">
      var disqus_shortname = 'bad-to-the-code';
      function disqus() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      }
  
      
      var hash = window.location.hash.substr(1);
      if ((hash.length > 8) && (hash.substring(0, 8) === "comment-")) {
        disqus();
        document.getElementById("show_comments").style.display = "none";
      } else {
        document.getElementById('load_comments').onclick = function() {
          disqus();
          document.getElementById("show_comments").style.display = "none";
        };
      }
  

    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
  </div>
</section>


<section class="section">
  <div class="container has-text-centered">
    <p>&copy; <a href="https://github.com/madcap1090">William Bourgeois</a> 2020</p>
    
      <p>Powered by <a href="https://gohugo.io/">Hugo</a> &amp; <a href="https://github.com/ribice/kiss">Kiss</a>.</p>
    
  </div>
</section>


<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
	ga('create', 'UA-137981534-1', 'auto');
	
	ga('send', 'pageview');
}
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>


<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="\/\/matomo.example.com\/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript>
  <img src="//matomo.example.com/piwik.php?idsite=1&amp;rec=1" style="border:0" alt="" />
</noscript>


</body>
</html>

