---
title: am I getting slower going to work?
author: William Bourgeois
date: '2019-04-13'
slug: am-i-getting-slower-going-to-work
categories: 
  - geocoding
tags:
  - Geocoding
  - Google
---



<p>I got a bit distracted writing the last post. What I want to find out is, based on my Google location history, how fast I bike to work and if this has changed over time.</p>
<p>Attaching libraries</p>
<pre class="r"><code>library(&quot;tidyverse&quot;)
library(&quot;lubridate&quot;)
library(&quot;glue&quot;)
library(&quot;purrr&quot;)
library(&quot;ggmap&quot;)
library(&quot;ggplot2&quot;); theme_set(theme_minimal())</code></pre>
<p>And loading the data</p>
<pre class="r"><code># the code to convert your location data to a data frame:
# see last post too
# data &lt;- fromJSON(&quot;./data/Location History.json&quot;) # extracts a list
# locations &lt;- data$locations # and the list contains a dataframe

location &lt;- readRDS(&quot;~/R/blog/content/post/data/location.rds&quot;)

df &lt;- location %&gt;% 
  mutate(datetime = as.POSIXct(as.numeric(timestampMs)/1000, origin = &quot;1970-01-01&quot;)) 

df &lt;- df %&gt;% 
  mutate(lat   = latitudeE7/1e7,
         lon   = longitudeE7/1e7,
         time  = strftime(datetime, format = &quot;%H:%M:%S&quot;),
         date  = date(datetime),
         year  = year(datetime),
         month = month(datetime),
         wday  = wday(datetime))</code></pre>
<p>So what do we have here?</p>
<pre class="r"><code>nrow(df)                   # rows</code></pre>
<pre><code>## [1] 522770</code></pre>
<pre class="r"><code>length(unique(df$date))    # days</code></pre>
<pre><code>## [1] 1249</code></pre>
<pre class="r"><code>min(unique(df$date))       # first day</code></pre>
<pre><code>## [1] &quot;2014-01-14&quot;</code></pre>
<pre class="r"><code>max(unique(df$date))       # last day</code></pre>
<pre><code>## [1] &quot;2018-10-15&quot;</code></pre>
<p>Plotted:</p>
<pre class="r"><code>ggplot(data = df, aes(x = datetime, y = lat))+
 geom_line()+
  theme(axis.title.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
    labs(title=&quot;commuting slower?&quot;,
       subtitle = &quot;latitude tracking 2014 - 2018&quot;,
       x = &quot;days&quot;,
       y = &quot;latitude&quot;)</code></pre>
<p><img src="/post/2019-04-13-am-i-getting-slower-going-to-work_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>I changed jobs in September 2014, my first working day at my current job was 15/09/2014.</p>
<p>Let’s see which days I was working there. The dataframe “work”, then contains all the data points from where I am at work.</p>
<pre class="r"><code>work &lt;- df %&gt;% 
  filter(date &gt; &quot;2014-09-14&quot;) %&gt;%
  filter(round(lat,3) == 50.557) %&gt;% 
  filter(round(lon,2) == 5.18) %&gt;% # a little less accuracy on the longitude
  mutate(homework = &quot;work&quot;) %&gt;% 
  mutate(am_pm = case_when(am(datetime) ~ &quot;am&quot;,
                           TRUE ~ &quot;pm&quot;))

length(unique(work$date)) </code></pre>
<pre><code>## [1] 406</code></pre>
<pre class="r"><code>ggplot(data = work, aes(x = datetime, y = lat))+
  geom_line() +
  theme(axis.title.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())+
  labs(y = &quot;latitude&quot;, 
    title = &quot;lattitude between home and work by day&quot;)</code></pre>
<p><img src="/post/2019-04-13-am-i-getting-slower-going-to-work_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>So that would mean that in my data set I have 406 working days and the data that comes along with it.
Since at this point I am not interested in the data from days I was not working, these can be filtered out.</p>
<pre class="r"><code>home &lt;- df %&gt;%
  filter(round(lat,3) != 50.557) %&gt;% 
  filter(round(lon,2) != 5.18) %&gt;%
  mutate(homework = &quot;not_work&quot;) %&gt;% 
  filter(date %in%(unique(work$date))) %&gt;% 
  mutate(am_pm = case_when(am(datetime) ~ &quot;am&quot;,
                           TRUE ~ &quot;pm&quot;))</code></pre>
<p>Check if the dates are the same</p>
<pre class="r"><code>setdiff(unique(home$date),unique(work$date))  </code></pre>
<pre><code>## numeric(0)</code></pre>
<p>Nice. The dates are equal. The home and work date frames can be binded.</p>
<pre class="r"><code>home_work &lt;- rbind(home, work) %&gt;% 
  arrange(datetime)</code></pre>
<p>What days at work got tracked?</p>
<pre class="r"><code>length(unique(home_work$date)) # workdays</code></pre>
<pre><code>## [1] 406</code></pre>
<pre class="r"><code>min(unique(home_work$date))    # first day</code></pre>
<pre><code>## [1] &quot;2014-09-15&quot;</code></pre>
<pre class="r"><code>max(unique(home_work$date))    # last day</code></pre>
<pre><code>## [1] &quot;2018-07-03&quot;</code></pre>
<p>To calculate the time of my daily commute I have to find the time between I last was at home and the time I arrived at work.</p>
<p>The latitude changes during a typical working day look like this (although this one is particularly boring :unamused:).</p>
<pre class="r"><code>day &lt;- df %&gt;% 
  filter(date == &quot;2014-12-23&quot;) 

ggplot(data = day, aes(x = datetime, y = lat)) +
  geom_line() +
  theme(axis.title.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  labs(y = &quot;latitude&quot;, 
    title = &quot;23/12/2014 - another day at the office&quot;)</code></pre>
<p><img src="/post/2019-04-13-am-i-getting-slower-going-to-work_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>And if we look at the first hours of the day and arriving at work:</p>
<pre class="r"><code>day &lt;- df %&gt;% 
  filter(date == &quot;2014-12-23&quot;) %&gt;% 
  filter(time &gt; &quot;07:00:00&quot;,
         time &lt; &quot;09:30:00&quot;)

ggplot(data = day, aes(x = datetime, y = lat)) +
  geom_line() +
  theme(axis.title.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  labs(y = &quot;Latitude&quot;, 
    title = &quot;23/12/2014 - zooming in on arriving at work&quot;)</code></pre>
<p><img src="/post/2019-04-13-am-i-getting-slower-going-to-work_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>So the time spent in the commute is the time first at around 50.560 latitude (itw) minus the last time at around 50.580 latitude (oth), and that for the time period of let’s say between 7am and 9.30am.</p>
<pre class="r"><code>oth &lt;- day %&gt;% 
  filter(lat &lt; 50.5756) %&gt;% 
  filter(time == min(time)) %&gt;% 
  select(time) %&gt;% 
  mutate(time = as.POSIXct(time, format = &quot;%H:%M:%S&quot;))

itw &lt;- day %&gt;% 
  filter(lat &lt; 50.558) %&gt;% 
  filter(time == min(time)) %&gt;% 
  select(time)%&gt;% 
  mutate(time = as.POSIXct(time, format = &quot;%H:%M:%S&quot;))

commute_time &lt;- difftime(itw$time,oth$time, units = c(&quot;mins&quot;)) #9.93 minutes
class(commute_time)</code></pre>
<pre><code>## [1] &quot;difftime&quot;</code></pre>
<pre class="r"><code>as.numeric(commute_time)</code></pre>
<pre><code>## [1] 2.083333</code></pre>
<p>2 minutes is a bit too fast. The problem is that the first time out of the house, on that particular date, is recorded pretty late. So the last time in the house (ith) is the one that is needed. Also because starting around 30/01/2016 a strange pattern is emerging</p>
<pre class="r"><code>day &lt;- home_work %&gt;%
  filter(date == &quot;2018-07-03&quot;) %&gt;% 
  filter(time &gt; &quot;08:00:00&quot;,
         time &lt; &quot;09:30:00&quot;)

ggplot(data = day, aes(x = datetime, y = lat)) +
  geom_line() +
  theme(axis.title.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  labs(y = &quot;latitude&quot;, 
    title = &quot;&#39;bilocation&#39; pattern&quot;)</code></pre>
<p><img src="/post/2019-04-13-am-i-getting-slower-going-to-work_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>And that pattern did not happen before February 2016. For instance “2016-01-08” gives.</p>
<pre class="r"><code>day &lt;- home_work %&gt;%
  filter(date == &quot;2016-01-08&quot;) %&gt;% 
  filter(time &gt; &quot;07:30:00&quot;,
         time &lt; &quot;09:30:00&quot;)

ggplot(data = day, aes(x = datetime, y = lat)) +
  geom_line()+
  theme(axis.title.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  labs(y = &quot;latitude&quot;, 
    title = &quot;before February 2016&quot;)</code></pre>
<p><img src="/post/2019-04-13-am-i-getting-slower-going-to-work_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>A collegue came up with the hypothesis that it was my computer at home that was messing up my phone location data, which was a great idea, but in fact it was my tablet.</p>
<p>I bought it on 30/01/2016, and both it’s location data and my phone location data are merged ever since. Which is kind of surprising or rather dissapointing.</p>
<p>Google is serving us dirty data in the location history. I cannot imagine it does not distinguish between my devises.</p>
<pre class="r"><code>oth &lt;- day %&gt;% 
  filter(lat &lt; 50.5756) %&gt;% 
  filter(time == min(time)) %&gt;% 
  select(time) %&gt;% 
  mutate(time = as.POSIXct(time, format = &quot;%H:%M:%S&quot;))

# the last time in the house
ith &lt;- day %&gt;% 
  mutate(time = as.POSIXct(time, format = &quot;%H:%M:%S&quot;)) %&gt;% 
  filter(time &lt; oth$time) %&gt;% 
  filter(time == max(time))%&gt;% 
  select(time) %&gt;% 
  mutate(time = as.POSIXct(time, format = &quot;%H:%M:%S&quot;))


itw &lt;- day %&gt;% 
  filter(lat &lt; 50.557) %&gt;% 
  filter(time == min(time)) %&gt;% 
  select(time)%&gt;% 
  mutate(time = as.POSIXct(time, format = &quot;%H:%M:%S&quot;))

commute_time &lt;- difftime(itw$time,ith$time, units = c(&quot;mins&quot;)) #9.93 minutes
class(commute_time)</code></pre>
<pre><code>## [1] &quot;difftime&quot;</code></pre>
<pre class="r"><code>as.numeric(commute_time)</code></pre>
<pre><code>## [1] 44.48333</code></pre>
<p>17 minutes on the other hand seems a lot. But the data and calculations look correct to me. One explanation could be that sometimes there is a big delay in reporting the arrival time. Like on April 17 2015, where arrival was recorded after 12am.</p>
<pre class="r"><code>day &lt;- df %&gt;% 
  filter(date == &quot;2015-04-17&quot;) 

ggplot(data = day, aes(x = datetime, y = lat)) +
  geom_line() + 
  theme(axis.title.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  labs(y = &quot;latitude&quot;, 
    title = &quot;April 17 2015&quot;)</code></pre>
<p><img src="/post/2019-04-13-am-i-getting-slower-going-to-work_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>So it’s time to do some more data cleaning, and select dates that have data from both work and home between 7 and 9:30am.</p>
<pre class="r"><code>keep_dates &lt;- home_work %&gt;% 
  filter(time &gt; &quot;07:00:00&quot;,
         time &lt; &quot;09:30:00&quot;) %&gt;%
  plyr::count(c(&#39;date&#39;, &#39;homework&#39;)) %&gt;% 
  spread(homework, freq) %&gt;% 
  filter(work &gt; 0) %&gt;% 
  select(date)
glue(&quot;so there are now {nrow(keep_dates)} days to be analysed&quot;)</code></pre>
<pre><code>## so there are now 336 days to be analysed</code></pre>
<p>Let’s define a function to do it.</p>
<pre class="r"><code># building the function
get_time &lt;- function(x_date){
  day &lt;- home_work %&gt;%
    filter(date ==  x_date) %&gt;% 
    filter(time &gt; &quot;07:30:00&quot;,
           time &lt; &quot;09:30:00&quot;)
  oth &lt;- day %&gt;% 
    filter(lat &lt; 50.5756) %&gt;% 
    filter(time == min(time)) %&gt;% 
    select(time) %&gt;% 
    mutate(time = as.POSIXct(time, format = &quot;%H:%M:%S&quot;)) %&gt;% 
    slice(1) # making sure one value is returned
  
  ith &lt;- day %&gt;% 
    mutate(time = as.POSIXct(time, format = &quot;%H:%M:%S&quot;)) %&gt;% 
    filter(time &lt; oth$time) %&gt;% 
    filter(time == max(time))%&gt;% 
    select(time) %&gt;% 
    mutate(time = as.POSIXct(time, format = &quot;%H:%M:%S&quot;))
  
  if(nrow(ith) == 0) {ith &lt;- oth} 
  
  itw &lt;- day %&gt;% 
    filter(lat &lt; 50.558) %&gt;% 
    filter(time == min(time)) %&gt;% 
    select(time)%&gt;% 
    mutate(time = as.POSIXct(time, format = &quot;%H:%M:%S&quot;))%&gt;% 
    slice(1) # making sure one value is returned
  
  x &lt;- difftime(itw$time,ith$time, units = c(&quot;mins&quot;))
  x &lt;- round(as.numeric(x),2)
  return(x)
  
}</code></pre>
<p>I had a struggle with purrr’s map_df() , but map_dbl() also does the trick</p>
<pre class="r"><code>result &lt;- map_dbl(keep_dates$date, get_time) %&gt;% 
  as.data.frame() %&gt;% 
  rename(&quot;minutes&quot; = &quot;.&quot;) %&gt;% 
  cbind(keep_dates) %&gt;% 
  select(date, minutes)

head(result)</code></pre>
<pre><code>##         date minutes
## 1 2014-09-16   18.53
## 2 2014-09-18   10.45
## 3 2014-09-24   28.02
## 4 2014-09-26   32.77
## 5 2014-09-30    9.30
## 6 2014-10-01   20.92</code></pre>
<pre class="r"><code>max(result$minutes)</code></pre>
<pre><code>## [1] 100.95</code></pre>
<pre class="r"><code>min(result$minutes)</code></pre>
<pre><code>## [1] 0.13</code></pre>
<pre class="r"><code>ggplot(result, aes(x = date, y = minutes)) +
  geom_bar(stat = &quot;identity&quot;)+ 
  scale_y_continuous(limits = c(0, 65)) +
  labs(y = &quot;minutes to work&quot;, 
    title = &quot;2015 - 2018&quot;)</code></pre>
<p><img src="/post/2019-04-13-am-i-getting-slower-going-to-work_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>2018 seems to have the cleanest data at this point. I sometimes walk to work or take the bus or the car. All of these take me more time than biking to work. There are five trafic lights on the way and I tend to stop for trafic lights when they are red. So the trafic ligths might explain much of the variance.</p>
<p>A bike ride would not take more than twenty minutes, and surely not less than 5.</p>
<pre class="r"><code>r_2018 &lt;- result %&gt;% 
  filter(year(date) == 2018) %&gt;% 
  filter(minutes &lt; 20,
         minutes &gt; 5)

ggplot(r_2018, aes(x = date, y = minutes)) +
  geom_bar(stat = &quot;identity&quot;) +
  labs(y = &quot;minutes to work&quot;, 
    title = &quot;2018&quot;)</code></pre>
<p><img src="/post/2019-04-13-am-i-getting-slower-going-to-work_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<pre class="r"><code>round(mean(r_2018$minutes),2)</code></pre>
<pre><code>## [1] 12.18</code></pre>
<p>So that would then be around 12 minutes. I still need to time my current commutes for a while to see if I got slower.</p>
<p>I hoped for a bit cleaner data and the possibility to easyly compare the evolution of the time spent commuting over several years. But I’ll take the 12.18 minutes for now.</p>
<p>Finally I wanted to share the “patés” with you. Not often enough part of the team takes a break and walks around the office block, and those we call doing a “paté” (= block). They say walking meetings are in these days.</p>
<p>I was looking to see how many of them we are doing, but as you will see below the datapoints are mostly centered on our office building itself. And I cannot see how I can construct a pattern around it representing the “patés”.</p>
<pre class="r"><code>zoom &lt;- get_map(location = c(lon = 4.306, lat = 50.8545), zoom = 19, maptype = &quot;satellite&quot;)</code></pre>
<pre><code>## Source : https://maps.googleapis.com/maps/api/staticmap?center=50.8545,4.306&amp;zoom=19&amp;size=640x640&amp;scale=2&amp;maptype=satellite&amp;language=en-EN&amp;key=xxx</code></pre>
<pre class="r"><code>df &lt;- readRDS(&quot;~/R/blog/content/post/data/location_509.rds&quot;) %&gt;% 
  filter(year != 2017)

ggmap(zoom) + 
  geom_point(data = df, aes(x = lon, y = lat),
             alpha = 0.7, color = &quot;#FC4E07&quot;, size = .8) + 
  facet_wrap(~year) +
  theme(legend.position = &quot;right&quot;) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  labs(
    x = &quot;Longitude&quot;, 
    y = &quot;Latitude&quot;, 
    title = &quot;always happy @work&quot;,
    caption = &quot;\n removed 2017 because there were few data points.&quot;)</code></pre>
<p><img src="/post/2019-04-13-am-i-getting-slower-going-to-work_files/figure-html/unnamed-chunk-26-1.png" width="960" /></p>
<p>It seems to me all the data is a bit off. 2014 to 2016 a bit or a lot shifted to the left, and 2018 just a tad too much to the left.</p>
<p>But still. Welcome to the panopticon.</p>
