---
title: r u bot or not bot?
author: William Bourgeois
date: '2019-09-27'
slug: r-u-bot-or-not-bot
categories: []
tags:
  - Twitter
  - Network analysis
---

If you have a Twitter account chances are one day you had a new follower that felt a bit weird. Maybe the account has few followers, a lot or no tweets, recent created profile, 

Just setting up my Twitter. #myfirstTweet

Just setting up my Twitter. #myfirstTweet

Not followed by anyone you're following

Or you just cannot understand why that account should want to follow you because you have no connections whatsoever. 

It is likely that these accounts are managed by bots using the Twitter API. Since it is estimated that 15% of profiles on Twitter are controled by bots and that there has been a lot of speculation on their political influence through their propagation of propaganda, 


Font Size: 
Online Human-Bot Interactions: Detection, Estimation, and Characterization
Onur Varol, Emilio Ferrara, Clayton A. Davis, Filippo Menczer, Alessandro Flammini

Last modified: 2017-05-03
Abstract

Increasing evidence suggests that a growing amount of social media content is generated by autonomous entities known as social bots. In this work we present a framework to detect such entities on Twitter. We leverage more than a thousand features extracted from public data and meta-data about users: friends, tweet content and sentiment, network patterns, and activity time series. We benchmark the classification framework by using a publicly available dataset of Twitter bots. This training data is enriched by a manually annotated collection of active Twitter users that include both humans and bots of varying sophistication. Our models yield high accuracy and agreement with each other and can detect bots of different nature. Our estimates suggest that between 9% and 15% of active Twitter accounts are bots. Characterizing ties among accounts, we observe that simple bots tend to interact with bots that exhibit more human-like behaviors. Analysis of content flows reveals retweet and mention strategies adopted by bots to interact with different target groups. Using clustering analysis, we characterize several subclasses of accounts, including spammers, self promoters, and accounts that post content from connected applications.

Full Text: PDF