---
title: Belgian parliamentarians tweets
author: William Bourgeois
date: '2019-05-03'
slug: belgian-parliamentarians-tweets
categories: []
tags:
  - Belgian politics
  - Twitter
---



<p>In the last post we were pretty successful in getting our parliamentarians Twitter handles. We can now use these to download their tweets.</p>
<p>The twitter API allows to download 3200 tweets per handle. This means that we will not be able to download all tweets of all parliamentarians from the last five years, because some of them tweeted more than 3200 during that time period. But there will be a fair amount.</p>
<p>These tweets will also have to be ‘cleaned’ of special characters like emojis and links in order to analyse them further without the different packages choking on them.</p>
<p>As usually first the libraries and options:</p>
<pre class="r"><code>library(&quot;tidyverse&quot;)</code></pre>
<pre><code>## -- Attaching packages ---------------------------------------------------------- tidyverse 1.2.1 --</code></pre>
<pre><code>## v ggplot2 3.1.1       v purrr   0.3.1  
## v tibble  2.0.1       v dplyr   0.8.0.1
## v tidyr   0.8.3       v stringr 1.4.0  
## v readr   1.3.1       v forcats 0.3.0</code></pre>
<pre><code>## -- Conflicts ------------------------------------------------------------- tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>library(&quot;gmp&quot;)</code></pre>
<pre><code>## 
## Attaching package: &#39;gmp&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     %*%, apply, crossprod, matrix, tcrossprod</code></pre>
<pre class="r"><code>library(&quot;glue&quot;)</code></pre>
<pre><code>## 
## Attaching package: &#39;glue&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     collapse</code></pre>
<pre class="r"><code>library(&quot;rtweet&quot;)</code></pre>
<pre><code>## 
## Attaching package: &#39;rtweet&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     flatten</code></pre>
<pre class="r"><code>library(&quot;cld2&quot;) 
library(&quot;textcat&quot;)
library(&quot;qdapRegex&quot;)</code></pre>
<pre><code>## 
## Attaching package: &#39;qdapRegex&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     explain</code></pre>
<pre><code>## The following object is masked from &#39;package:ggplot2&#39;:
## 
##     %+%</code></pre>
<pre class="r"><code># options 

options(scipen=999)
stringAsFactors = FALSE</code></pre>
<p>And here is the function to get the tweets (for now just 1 for testing, because 3200 tweets takes a while):</p>
<pre class="r"><code>get_handle_tweets &lt;- function(handle) {
  tweets_handle &lt;&lt;- get_timeline(handle, n=1)
  n &lt;- nrow(tweets_handle)
    print(glue(&quot;{handle} {n} tweets added&quot;))
}</code></pre>
<p>And a function to clean the tweets:</p>
<pre class="r"><code>to_byte &lt;- function (x) {
  Encoding(x) &lt;- &quot;latin1&quot;
  iconv(x, &quot;latin1&quot;, &quot;ASCII&quot;, &quot;byte&quot;)
}</code></pre>
<p>Here are the handles:</p>
<pre class="r"><code>twitter_users &lt;- readRDS(&quot;~/R/blogs/content/post/data/20190502/twitter_users.rds&quot;)</code></pre>
<p>A test</p>
<pre class="r"><code>twitter_users$screen_name[3]</code></pre>
<pre><code>## [1] &quot;wbeke&quot;</code></pre>
<pre class="r"><code>names(twitter_users$screen_name[3])</code></pre>
<pre><code>## NULL</code></pre>
<p>It’s not stictly needed since we already know the correspondence between name and handle (‘screen_name’), but it’s fun to try map2_df.</p>
<pre class="r"><code>get_handle_tweets &lt;- function(screen_name, ln_fn) {
  get_timeline(screen_name, n=2) %&gt;% 
    mutata(ln_fn = ln_fn)
}

tweets &lt;- map2_df(twitter_users$screen_name,twitter_users$ln_fn, 
             possibly(get_handle_tweets, otherwise = NULL))
dim(tweets)</code></pre>
<pre><code>## [1] 0 0</code></pre>
<p>Now might be a good time to talk about rate limits. We are limited to go 3200 tweets in the past per handle, but we have also temporary limits to the calls we can do with the API.</p>
<pre class="r"><code>limits &lt;- rate_limits()
limits</code></pre>
<pre><code>## # A tibble: 149 x 7
##    query limit remaining reset reset_at            timestamp          
##    &lt;chr&gt; &lt;int&gt;     &lt;int&gt; &lt;tim&gt; &lt;dttm&gt;              &lt;dttm&gt;             
##  1 list~    15        15 15.0~ 2019-05-05 14:52:30 2019-05-05 14:37:28
##  2 list~    75        75 15.0~ 2019-05-05 14:52:30 2019-05-05 14:37:28
##  3 list~    15        15 15.0~ 2019-05-05 14:52:30 2019-05-05 14:37:28
##  4 list~   900       900 15.0~ 2019-05-05 14:52:30 2019-05-05 14:37:28
##  5 list~    15        15 15.0~ 2019-05-05 14:52:30 2019-05-05 14:37:28
##  6 list~    75        75 15.0~ 2019-05-05 14:52:30 2019-05-05 14:37:28
##  7 list~    15        15 15.0~ 2019-05-05 14:52:30 2019-05-05 14:37:28
##  8 list~   180       180 15.0~ 2019-05-05 14:52:30 2019-05-05 14:37:28
##  9 list~    15        15 15.0~ 2019-05-05 14:52:30 2019-05-05 14:37:28
## 10 list~   900       900 15.0~ 2019-05-05 14:52:30 2019-05-05 14:37:28
## # ... with 139 more rows, and 1 more variable: app &lt;chr&gt;</code></pre>
<p>In total there are 149 limits, we can access, amongst other things, how much remains and when the limit will be reset. Here are the limits:</p>
<pre class="r"><code>limits$query</code></pre>
<pre><code>##   [1] &quot;lists/list&quot;                                                      
##   [2] &quot;lists/memberships&quot;                                               
##   [3] &quot;lists/subscribers/show&quot;                                          
##   [4] &quot;lists/members&quot;                                                   
##   [5] &quot;lists/subscriptions&quot;                                             
##   [6] &quot;lists/show&quot;                                                      
##   [7] &quot;lists/ownerships&quot;                                                
##   [8] &quot;lists/subscribers&quot;                                               
##   [9] &quot;lists/members/show&quot;                                              
##  [10] &quot;lists/statuses&quot;                                                  
##  [11] &quot;application/rate_limit_status&quot;                                   
##  [12] &quot;mutes/users/list&quot;                                                
##  [13] &quot;mutes/users/ids&quot;                                                 
##  [14] &quot;live_video_stream/status/:id&quot;                                    
##  [15] &quot;friendships/outgoing&quot;                                            
##  [16] &quot;friendships/list&quot;                                                
##  [17] &quot;friendships/no_retweets/ids&quot;                                     
##  [18] &quot;friendships/lookup&quot;                                              
##  [19] &quot;friendships/incoming&quot;                                            
##  [20] &quot;friendships/show&quot;                                                
##  [21] &quot;guide&quot;                                                           
##  [22] &quot;auth/csrf_token&quot;                                                 
##  [23] &quot;blocks/list&quot;                                                     
##  [24] &quot;blocks/ids&quot;                                                      
##  [25] &quot;geo/similar_places&quot;                                              
##  [26] &quot;geo/id/:place_id&quot;                                                
##  [27] &quot;geo/reverse_geocode&quot;                                             
##  [28] &quot;geo/search&quot;                                                      
##  [29] &quot;users/report_spam&quot;                                               
##  [30] &quot;users/contributors/pending&quot;                                      
##  [31] &quot;users/show/:id&quot;                                                  
##  [32] &quot;users/search&quot;                                                    
##  [33] &quot;users/suggestions/:slug&quot;                                         
##  [34] &quot;users/contributees/pending&quot;                                      
##  [35] &quot;users/derived_info&quot;                                              
##  [36] &quot;users/profile_banner&quot;                                            
##  [37] &quot;users/suggestions/:slug/members&quot;                                 
##  [38] &quot;users/lookup&quot;                                                    
##  [39] &quot;users/suggestions&quot;                                               
##  [40] &quot;followers/ids&quot;                                                   
##  [41] &quot;followers/list&quot;                                                  
##  [42] &quot;collections/list&quot;                                                
##  [43] &quot;collections/entries&quot;                                             
##  [44] &quot;collections/show&quot;                                                
##  [45] &quot;statuses/retweeters/ids&quot;                                         
##  [46] &quot;statuses/retweets_of_me&quot;                                         
##  [47] &quot;statuses/home_timeline&quot;                                          
##  [48] &quot;statuses/show/:id&quot;                                               
##  [49] &quot;statuses/user_timeline&quot;                                          
##  [50] &quot;statuses/friends&quot;                                                
##  [51] &quot;statuses/retweets/:id&quot;                                           
##  [52] &quot;statuses/mentions_timeline&quot;                                      
##  [53] &quot;statuses/oembed&quot;                                                 
##  [54] &quot;statuses/lookup&quot;                                                 
##  [55] &quot;custom_profiles/list&quot;                                            
##  [56] &quot;custom_profiles/show&quot;                                            
##  [57] &quot;webhooks/subscriptions/direct_messages&quot;                          
##  [58] &quot;webhooks&quot;                                                        
##  [59] &quot;contacts/uploaded_by&quot;                                            
##  [60] &quot;contacts/users&quot;                                                  
##  [61] &quot;contacts/addressbook&quot;                                            
##  [62] &quot;contacts/users_and_uploaded_by&quot;                                  
##  [63] &quot;contacts/delete/status&quot;                                          
##  [64] &quot;labs/:version/users&quot;                                             
##  [65] &quot;labs/:version/tweets&quot;                                            
##  [66] &quot;i/config&quot;                                                        
##  [67] &quot;tweet_prompts/report_interaction&quot;                                
##  [68] &quot;tweet_prompts/show&quot;                                              
##  [69] &quot;moments/statuses/update&quot;                                         
##  [70] &quot;moments/permissions&quot;                                             
##  [71] &quot;help/tos&quot;                                                        
##  [72] &quot;help/configuration&quot;                                              
##  [73] &quot;help/privacy&quot;                                                    
##  [74] &quot;help/settings&quot;                                                   
##  [75] &quot;help/languages&quot;                                                  
##  [76] &quot;feedback/show/:id&quot;                                               
##  [77] &quot;feedback/events&quot;                                                 
##  [78] &quot;business_experience/dashboard_settings/destroy&quot;                  
##  [79] &quot;business_experience/dashboard_features&quot;                          
##  [80] &quot;business_experience/keywords&quot;                                    
##  [81] &quot;business_experience/dashboard_settings/update&quot;                   
##  [82] &quot;business_experience/dashboard_settings/show&quot;                     
##  [83] &quot;graphql&amp;POST&quot;                                                    
##  [84] &quot;friends/following/ids&quot;                                           
##  [85] &quot;friends/following/list&quot;                                          
##  [86] &quot;friends/list&quot;                                                    
##  [87] &quot;friends/ids&quot;                                                     
##  [88] &quot;sandbox/account_activity/webhooks/:id/subscriptions&quot;             
##  [89] &quot;drafts/statuses/update&quot;                                          
##  [90] &quot;drafts/statuses/destroy&quot;                                         
##  [91] &quot;drafts/statuses/ids&quot;                                             
##  [92] &quot;drafts/statuses/list&quot;                                            
##  [93] &quot;drafts/statuses/show&quot;                                            
##  [94] &quot;drafts/statuses/create&quot;                                          
##  [95] &quot;direct_messages/sent&quot;                                            
##  [96] &quot;direct_messages/broadcasts/list&quot;                                 
##  [97] &quot;direct_messages/subscribers/lists/members/show&quot;                  
##  [98] &quot;direct_messages/mark_read&quot;                                       
##  [99] &quot;direct_messages/subscribers/ids&quot;                                 
## [100] &quot;direct_messages/sent_and_received&quot;                               
## [101] &quot;direct_messages/broadcasts/statuses/list&quot;                        
## [102] &quot;direct_messages&quot;                                                 
## [103] &quot;direct_messages/subscribers/lists/members/ids&quot;                   
## [104] &quot;direct_messages/subscribers/show&quot;                                
## [105] &quot;direct_messages/broadcasts/show&quot;                                 
## [106] &quot;direct_messages/broadcasts/statuses/show&quot;                        
## [107] &quot;direct_messages/subscribers/lists/list&quot;                          
## [108] &quot;direct_messages/show&quot;                                            
## [109] &quot;direct_messages/events/list&quot;                                     
## [110] &quot;direct_messages/subscribers/lists/show&quot;                          
## [111] &quot;direct_messages/events/show&quot;                                     
## [112] &quot;media/upload&quot;                                                    
## [113] &quot;traffic/map&quot;                                                     
## [114] &quot;account_activity/all/webhooks&quot;                                   
## [115] &quot;account_activity/all/:instance_name/subscriptions&quot;               
## [116] &quot;account_activity/direct_messages/webhooks&quot;                       
## [117] &quot;account_activity/webhooks/:id/subscriptions/direct_messages/list&quot;
## [118] &quot;account_activity/webhooks/:id/subscriptions/all&quot;                 
## [119] &quot;account_activity/direct_messages/:instance_name/webhooks&quot;        
## [120] &quot;account_activity/webhooks/:id/subscriptions/all/list&quot;            
## [121] &quot;account_activity/webhooks/:id/subscriptions/direct_messages&quot;     
## [122] &quot;account_activity/webhooks&quot;                                       
## [123] &quot;account_activity/direct_messages/:instance_name/subscriptions&quot;   
## [124] &quot;account_activity/webhooks/:id/subscriptions&quot;                     
## [125] &quot;account_activity/all/:instance_name/webhooks&quot;                    
## [126] &quot;account/login_verification_enrollment&quot;                           
## [127] &quot;account/update_profile&quot;                                          
## [128] &quot;account/verify_credentials&quot;                                      
## [129] &quot;account/settings&quot;                                                
## [130] &quot;safety/detection_feedback&quot;                                       
## [131] &quot;favorites/list&quot;                                                  
## [132] &quot;device/token&quot;                                                    
## [133] &quot;tweets/stream/filter/rules&quot;                                      
## [134] &quot;tweets/stream/filter/:instance_name&quot;                             
## [135] &quot;tweets/search/:product/:label&quot;                                   
## [136] &quot;tweets/search/:product/:instance/counts&quot;                         
## [137] &quot;tweets/stream/filter/rules/:instance_name/validation&amp;POST&quot;       
## [138] &quot;tweets/stream/filter/rules/:instance_name&amp;POST&quot;                  
## [139] &quot;tweets/stream/filter/rules/:instance_name&amp;DELETE&quot;                
## [140] &quot;tweets/stream/filter/rules/:instance_name/:rule_id&quot;              
## [141] &quot;saved_searches/destroy/:id&quot;                                      
## [142] &quot;saved_searches/show/:id&quot;                                         
## [143] &quot;saved_searches/list&quot;                                             
## [144] &quot;oauth/invalidate_token&quot;                                          
## [145] &quot;search/tweets&quot;                                                   
## [146] &quot;trends/closest&quot;                                                  
## [147] &quot;trends/available&quot;                                                
## [148] &quot;trends/place&quot;                                                    
## [149] &quot;live_pipeline/events&quot;</code></pre>
<p>At this point we need to keep an eye on limits tweets (#49) and limits queries (#11).</p>
<pre class="r"><code>limits %&gt;% select(limit, query, remaining, reset) %&gt;% 
  filter(query ==  &quot;application/rate_limit_status&quot;|
          query ==  &quot;statuses/user_timeline&quot;) %&gt;% 
  mutate(reset = round(reset, 2))</code></pre>
<pre><code>## # A tibble: 2 x 4
##   limit query                         remaining reset     
##   &lt;int&gt; &lt;chr&gt;                             &lt;int&gt; &lt;time&gt;    
## 1   180 application/rate_limit_status        19 13.62 mins
## 2   900 statuses/user_timeline              740 13.62 mins</code></pre>
<p>We are searching 160 users and the rate limit for searching user timelines is 900, so we should be fine. But be aware that your limit searches are limited also (180 searches counted by individual limit in batches of 15 minutes).</p>
<p>At a certain point in time it might be useful to periodically query certain limits and to then pause the code in order not to produce interuptions.</p>
<p>How well did our test go? Did we get tweets from everyone?</p>
<pre class="r"><code>setdiff(twitter_users$ln_fn, tweets$ln_fn)</code></pre>
<pre><code>## Warning: Unknown or uninitialised column: &#39;ln_fn&#39;.</code></pre>
<pre><code>##   [1] &quot;Almaci Meyrem&quot;             &quot;Becq Sonja&quot;               
##   [3] &quot;Beke Wouter&quot;               &quot;Bellens Rita&quot;             
##   [5] &quot;Ben Hamou Nawal&quot;           &quot;Blanchart Philippe&quot;       
##   [7] &quot;Bogaert Hendrik&quot;           &quot;Bracke Siegfried&quot;         
##   [9] &quot;Burton Emmanuel&quot;           &quot;Buysrogge Peter&quot;          
##  [11] &quot;Calomne Gautier&quot;           &quot;Calvo Kristof&quot;            
##  [13] &quot;Capoen An&quot;                 &quot;Caprasse Véronique&quot;       
##  [15] &quot;Carcaci Aldo&quot;              &quot;Casier Youro&quot;             
##  [17] &quot;Chastel Olivier&quot;           &quot;Clarinval David&quot;          
##  [19] &quot;Corthouts Michel&quot;          &quot;Daerden Frédéric&quot;         
##  [21] &quot;Dallemagne Georges&quot;        &quot;De Coninck Monica&quot;        
##  [23] &quot;De Coninck Inez&quot;           &quot;De Crom Sandrine&quot;         
##  [25] &quot;de Lamotte Michel&quot;         &quot;De Roover Peter&quot;          
##  [27] &quot;De Vriendt Wouter&quot;         &quot;De Wever Bart&quot;            
##  [29] &quot;De Wit Sophie&quot;             &quot;Dedecker Peter&quot;           
##  [31] &quot;Dedry Anne&quot;                &quot;Degroote Koenraad&quot;        
##  [33] &quot;Delizée Jean-Marc&quot;         &quot;Demir Zuhal&quot;              
##  [35] &quot;Demon Franky&quot;              &quot;Deseyn Roel&quot;              
##  [37] &quot;Dewael Patrick&quot;            &quot;Dewinter Filip&quot;           
##  [39] &quot;Di Rupo Elio&quot;              &quot;Dispa Benoît&quot;             
##  [41] &quot;Dumery Daphné&quot;             &quot;Flahaux Jean-Jacques&quot;     
##  [43] &quot;Fonck Catherine&quot;           &quot;Foret Gilles&quot;             
##  [45] &quot;Frédéric André&quot;            &quot;Francken Theo&quot;            
##  [47] &quot;Friart Benoît&quot;             &quot;Gabriëls Katja&quot;           
##  [49] &quot;Gantois Rita&quot;              &quot;Gilkinet Georges&quot;         
##  [51] &quot;Goffin Philippe&quot;           &quot;Grosemans Karolien&quot;       
##  [53] &quot;Grovonius Gwenaëlle&quot;       &quot;Hedebouw Raoul&quot;           
##  [55] &quot;Heeren Veerle&quot;             &quot;Jadin Kattrin&quot;            
##  [57] &quot;Jambon Jan&quot;                &quot;Jiroflée Karin&quot;           
##  [59] &quot;Kir Emir&quot;                  &quot;Kitir Meryame&quot;            
##  [61] &quot;Laaouej Ahmed&quot;             &quot;Lachaert Egbert&quot;          
##  [63] &quot;Lalieux Karine&quot;            &quot;Lambrecht Annick&quot;         
##  [65] &quot;Lanjri Nahima&quot;             &quot;Lijnen Nele&quot;              
##  [67] &quot;Lutgen Benoît&quot;             &quot;Luykx Peter&quot;              
##  [69] &quot;Maingain Olivier&quot;          &quot;Nollet Jean-Marc&quot;         
##  [71] &quot;Onkelinx Laurette&quot;         &quot;Özen Özlem&quot;               
##  [73] &quot;Pas Barbara&quot;               &quot;Penris Jan&quot;               
##  [75] &quot;Piedboeuf Benoît&quot;          &quot;Schepmans Françoise&quot;      
##  [77] &quot;Schlitz Sarah&quot;             &quot;Scourneau Vincent&quot;        
##  [79] &quot;Senesael Daniel&quot;           &quot;Smaers Griet&quot;             
##  [81] &quot;Somers Ine&quot;                &quot;Spooren Jan&quot;              
##  [83] &quot;Temmerman Karin&quot;           &quot;Terwingen Raf&quot;            
##  [85] &quot;Thiébaut Eric&quot;             &quot;Thiéry Damien&quot;            
##  [87] &quot;Thoron Stéphanie&quot;          &quot;Uyttersprot Goedele&quot;      
##  [89] &quot;Van Biesen Luk&quot;            &quot;Van Camp Yoleen&quot;          
##  [91] &quot;Van Cauter Carina&quot;         &quot;Van der Maelen Dirk&quot;      
##  [93] &quot;Van Hecke Stefaan&quot;         &quot;Van Hees Marco&quot;           
##  [95] &quot;Van Hoof Els&quot;              &quot;Van Mechelen Dirk&quot;        
##  [97] &quot;Van Peel Valerie&quot;          &quot;Van Peteghem Vincent&quot;     
##  [99] &quot;Van Vaerenbergh Kristien&quot;  &quot;Vanden Burre Gilles&quot;      
## [101] &quot;Vandenput Tim&quot;             &quot;Vandeput Steven&quot;          
## [103] &quot;Vercamer Stefaan&quot;          &quot;Vercammen Jan&quot;            
## [105] &quot;Verherstraeten Servais&quot;    &quot;Vermeulen Brecht&quot;         
## [107] &quot;Vuye Hendrik&quot;              &quot;Waterschoot Véronique&quot;    
## [109] &quot;Willaert Evita&quot;            &quot;Winckel Fabienne&quot;         
## [111] &quot;Wollants Bert&quot;             &quot;Wouters Veerle&quot;           
## [113] &quot;Yüksel Veli&quot;               &quot;Bacquelaine Daniel&quot;       
## [115] &quot;Claerhout Sarah&quot;           &quot;Crusnière Stéphane&quot;       
## [117] &quot;De Block Maggie&quot;           &quot;De Crem Pieter&quot;           
## [119] &quot;De Croo Alexander&quot;         &quot;Demeyer Willy&quot;            
## [121] &quot;Ducarme Denis&quot;             &quot;Flahaut André&quot;            
## [123] &quot;Fremault Céline&quot;           &quot;Geens Koen&quot;               
## [125] &quot;Hellings Benoit&quot;           &quot;Hufkens Renate&quot;           
## [127] &quot;Khattabi Zakia&quot;            &quot;Klaps Johan&quot;              
## [129] &quot;Lahaye-Battheu Sabien&quot;     &quot;Massin Eric&quot;              
## [131] &quot;Michel Charles&quot;            &quot;Poncelet Isabelle&quot;        
## [133] &quot;Raskin Wouter&quot;             &quot;Reynders Didier&quot;          
## [135] &quot;Turtelboom Annemie&quot;        &quot;Van der Donckt Wim&quot;       
## [137] &quot;Vanheste Ann&quot;              &quot;Wathelet Melchior&quot;        
## [139] &quot;Wilmès Sophie&quot;             &quot;Chabot Jacques&quot;           
## [141] &quot;Fernandez Fernandez Julie&quot; &quot;Geerts David&quot;             
## [143] &quot;Henry Olivier&quot;             &quot;Janssen Werner&quot;           
## [145] &quot;Matz Vanessa&quot;              &quot;Metsu Koen&quot;               
## [147] &quot;Smeyers Sarah&quot;             &quot;Top Alain&quot;                
## [149] &quot;Cassart-Mailleux Caroline&quot; &quot;Ceysens Patricia&quot;         
## [151] &quot;Delannois Paul-Olivier&quot;    &quot;Dierick Leen&quot;             
## [153] &quot;Janssens Dirk&quot;             &quot;Miller Richard&quot;           
## [155] &quot;Muylle Nathalie&quot;           &quot;Van den Bergh Jef&quot;        
## [157] &quot;Van Quickenborne Vincent&quot;  &quot;Vanvelthoven Peter&quot;       
## [159] &quot;Marghem Marie-Christine&quot;   &quot;Pehlivan Fatma&quot;</code></pre>
<p>Nice. The results look ok too. Will now launch the bigger batch (3200) while out playing some :tennis: :badminton:</p>
<pre class="r"><code>twitter_users &lt;- twitter_users %&gt;% 
  arrange(screen_name) %&gt;% 
  distinct(screen_name, .keep_all = TRUE) # removing doubles if present

get_handle_tweets &lt;- function(screen_name, ln_fn) {
  print(screen_name)
  get_timeline(screen_name, n=3200) %&gt;% 
    mutate(ln_fn = ln_fn)
}

system.time(tweets &lt;- map2_df(twitter_users$screen_name,twitter_users$ln_fn, 
             possibly(get_handle_tweets, otherwise = NULL)))</code></pre>
<pre><code>## [1] &quot;AhmedLaaouej&quot;
## [1] &quot;AlainTop27&quot;
## [1] &quot;alexanderdecroo&quot;
## [1] &quot;ancapoen&quot;
## [1] &quot;andreflahaut&quot;
## [1] &quot;annededry&quot;
## [1] &quot;AnnVanheste&quot;
## [1] &quot;ATurtelboom&quot;
## [1] &quot;Barbara_Pas&quot;
## [1] &quot;Bart_DeWever&quot;
## [1] &quot;BellensRita&quot;
## [1] &quot;Benoitbp59&quot;
## [1] &quot;BenoitDispa&quot;
## [1] &quot;BenoitFriart&quot;
## [1] &quot;BenoitHellings&quot;
## [1] &quot;BenoitLutgen&quot;
## [1] &quot;BertWollants&quot;
## [1] &quot;BurtonEmmanuel&quot;
## [1] &quot;carcaci49&quot;
## [1] &quot;CarinaVanCauter&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;CarolineCassart&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;CasierYouro&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;catherinefonck&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;celinefremault&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;CharlesMichel&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;DamienThiery&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;DanBacquelaine&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;danielsenesael&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;DavidClarinval&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;ddumery&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;DeWitSophie&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;dirkjanssens19&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;DirkVanMechele1&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;dirkvdmaelen&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;dreynders&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;ducarmedenis&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;egbertlachaert&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;eliodirupo&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;ElsVanHoofcdenv&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;emir_kir&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;EricMassin&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;EricThiebaut&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;EvitaWillaert&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;FabienneWinckel&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;FDW_VB&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;FlahauxMRI&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;FranckenTheo&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;FrankyDemon&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;FredericDaerden&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;FredericLeChat&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;fschepmans&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;G_Dallemagne&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;G_Uyttersprot&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;GautierCalomne&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;GeertsDavid&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;GeorgesGilkinet&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;Gilles_VDB&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;gillesforet&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;Gwengrovonius&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;hendrikbogaert&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;HendrikVuye&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;IneSomers&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;inez_deconinck&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;isabellepon&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;jacques_chabot&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;JanJambon&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;JanPenris&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;JanVercammenNVA&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;jefvandenbergh&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;jmdelizee&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;jmnollet&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;JohanKlaps&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;juliee710&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;karinelalieux&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;KarinJiroflee&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;karintemmerman&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;KaroGrosemans&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;katja_gabriels&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;KattrinJadin&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;Koen_Geens1&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;koenraaddegroo1&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;kris10vanvaer&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;kristofcalvo&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;LambrechtAnnick&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;leendierick&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;LijnenNele&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;LOnkelinx&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;LukVanBiesen&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;Maggie_DeBlock&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;Marco_VanHees&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;McMarghem&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;MeryameKitir&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;MeyremAlmaci&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;MicheldeLamotte&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;millerrichardmr&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;MonicaDeConinck&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;NahimaLanjri&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;nathaliemuylle&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;nawalbenhamou&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;OChastel&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;Olihen&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;OlivierMaingain&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;OzlemOzen1&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;patriciaceysens&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;PatrickDewael&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;peerlux&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;pehlivan_fatma&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;PeterBuysrogge&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;peterdedecker&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;PeterDeRoover1&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;Phgoffin&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;PhilBlanchart&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;pieterdecrem&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;podelannois&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;Rafterwingen&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;RaoulHedebouw&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;RaskinWouter&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;RenateHufkens&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;RitaGantois1&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;roeldeseyn&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;sandrinedecrom&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;Sarah_Claerhout&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;SarahSchlitz&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;SBattheu&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;scourneau&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;ServaisV&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;sky39119&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;SmaersGriet&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;smeyers1994&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;SonjaBecq&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;Sophie_Wilmes&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;SoVandeWoestyne&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;SpoorenJan&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;Stefaanvercamer&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;Steph_Crusniere&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;sthbracke&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;svandeput&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;SVHecke&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;ThoronStephanie&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;TimVandenput&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;Univers80&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;valerievanpeel&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;vanderdoncktwim&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;VanessaMatz24&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;VCaprasse&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;Veerle_Wouters&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;veerleheeren&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;veliyuksel&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;VermeulenBrecht&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;VeroWaterschoot&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;vincent_v_p&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;VincentVQ&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;VvelthovenPeter&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;wbeke&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;WernerJanssen00&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;Willy_Demeyer&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;WouterDeVriendt&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;YoleenVanCamp&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;ZakiaKhattabi&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>## [1] &quot;Zu_Demir&quot;</code></pre>
<pre><code>## Warning: Rate limit exceeded - 88</code></pre>
<pre><code>##    user  system elapsed 
##   73.25    0.97  167.22</code></pre>
<pre class="r"><code>dim(tweets)</code></pre>
<pre><code>## [1] 27237    89</code></pre>
<pre class="r"><code>saveRDS(tweets, &quot;./data/20190503/tweets.rds&quot;)</code></pre>
<p>Cool, so about 260K tweets.</p>
<p>But as already mentioned these are some of the tweets from people who at some time were in the 54th legistlature. They are not always a tweet from a person actually seating in parliament.</p>
<p>This wikipedia <a href="https://nl.wikipedia.org/wiki/Kamer_van_volksvertegenwoordigers_(samenstelling_2014-2019)#Lijst_van_volksvertegenwoordigers">page</a> has a good overview of the changes that occured since May 2014.</p>
