<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"  lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1"/>

<title>google location tracking | bad to the code</title>

<meta property='og:title' content='google location tracking - bad to the code'>
<meta property='og:description' content='Biking to work this week I was wondering if I had not gotten slower and if my commute was not taking longer than before. Not being a regular user of Strava or a similar app, I wondered if I could find an answer to that question using my Google location history.
So I downloaded the data, that comes in json format, and had a go at it. You can download your Google location data from your Google account.'>
<meta property='og:url' content='/post/google-location-tracking/'>
<meta property='og:site_name' content='bad to the code'>
<meta property='og:type' content='article'><meta property='og:image' content='https://www.gravatar.com/avatar/5f460ebf37e30791f47bb5be3de73e3a?s=256'><meta property='article:author' content='https://facebook.com/OClassicoOficial/videos/391802167961744/'><meta property='article:section' content='Post'><meta property='article:tag' content='R Markdown'><meta property='article:tag' content='Google'><meta property='article:tag' content='Geocoding'><meta property='article:published_time' content='2019-03-30T00:00:00Z'/><meta property='article:modified_time' content='2019-03-30T00:00:00Z'/><meta name='twitter:card' content='summary'><meta name='twitter:site' content='@WilliamBourgeoi'><meta name='twitter:creator' content='@WilliamBourgeoi'>


<link href="/index.xml" rel="alternate" type="application/rss+xml" title="bad to the code" />

<link rel="stylesheet" href="/css/style.css"/><link rel='stylesheet' href='/css/custom.css'><link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
</head>
<body>
<section class="section">
  <div class="container">
    <nav class="nav">
      <div class="nav-left">
        <a class="nav-item" href="/">
          <h1 class="title is-4">bad to the code</h1>
        </a>
      </div>
      <div class="nav-right">
        <nav class="nav-item level is-mobile"><a class="level-item" aria-label="facebook" href='https://facebook.com/OClassicoOficial/videos/391802167961744/'
            target='_blank' rel='noopener'>
            <span class="icon">
              <i class><svg viewbox='0 0 24 24' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' aria-hidden='true'>
    
    <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"/>
    
  </svg></i>
            </span>
          </a><a class="level-item" aria-label="email" href='mailto:madcap1090@gmail.com'
            target='_blank' rel='noopener'>
            <span class="icon">
              <i class><svg viewbox='0 0 24 24' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' aria-hidden='true'>
    
    <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/>
    <polyline points="22,6 12,13 2,6"/>
    
  </svg></i>
            </span>
          </a><a class="level-item" aria-label="linkedin" href='https://linkedin.com/in/williambourgeois'
            target='_blank' rel='noopener'>
            <span class="icon">
              <i class><svg viewbox='0 0 24 24' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' aria-hidden='true'>
    
    <path stroke-width="1.8" d="m5.839218,4.101561c0,1.211972 -0.974141,2.194011 -2.176459,2.194011s-2.176459,-0.982039 -2.176459,-2.194011c0,-1.211094 0.974141,-2.194011 2.176459,-2.194011s2.176459,0.982917 2.176459,2.194011zm0.017552,3.94922l-4.388022,0l0,14.04167l4.388022,0l0,-14.04167zm7.005038,0l-4.359939,0l0,14.04167l4.360816,0l0,-7.370999c0,-4.098413 5.291077,-4.433657 5.291077,0l0,7.370999l4.377491,0l0,-8.89101c0,-6.915523 -7.829986,-6.66365 -9.669445,-3.259423l0,-1.891237z"/>
    
  </svg></i>
            </span>
          </a><a class="level-item" aria-label="twitter" href='https://twitter.com/WilliamBourgeoi'
            target='_blank' rel='noopener'>
            <span class="icon">
              <i class><svg viewbox='0 0 24 24' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' aria-hidden='true'>
    
    <path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"/>
    
  </svg></i>
            </span>
          </a><a class="level-item" aria-label="github" href='https://github.com/madcap1090'
            target='_blank' rel='noopener'>
            <span class="icon">
              <i class><svg viewbox='0 0 24 24' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' aria-hidden='true'>
    
    <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"/>
    
  </svg></i>
            </span>
          </a></nav>
      </div>
    </nav>

    <nav class="nav">
      

      
    </nav>

  </div>
</section>
<section class="section">
  <div class="container">
    <div class="subtitle tags is-6 is-pulled-right">
      
      
<a class="subtitle is-6" href="/tags/r-markdown">#R Markdown</a>



  
  | <a class="subtitle is-6" href="/tags/google">#Google</a>
  
  | <a class="subtitle is-6" href="/tags/geocoding">#Geocoding</a>
  

      
    </div>
    <h2 class="subtitle is-6">March 30, 2019</h2>
    <h1 class="title">google location tracking</h1>
    
    <div class="content">
      


<p>Biking to work this week I was wondering if I had not gotten slower and if my commute was not taking longer than before. Not being a regular user of Strava or a similar app, I wondered if I could find an answer to that question using my Google location history.</p>
<p>So I downloaded the data, that comes in json format, and had a go at it. You can <a href="https://takeout.google.com/settings/takeout">download</a> your Google location data from your Google account.</p>
<p>Let’s load the data and attach the libraries that are needed.</p>
<pre class="r"><code>library(&quot;jsonlite&quot;)
library(&quot;tidyverse&quot;)
library(&quot;lubridate&quot;)
library(&quot;ggplot2&quot;)
library(&quot;ggmap&quot;)    # devtools::install_github(&quot;dkahle/ggmap&quot;)
library(&quot;glue&quot;)
library(&quot;emo&quot;)      # devtools::install_github(&quot;hadley/emo&quot;)</code></pre>
<pre class="r"><code>data &lt;- fromJSON(&quot;./data/Location History.json&quot;) # extracts a list
locations &lt;- data$locations # and the list contains a dataframe
rm(data)  # no need for this anymore</code></pre>
<p>This <a href="https://shiring.github.io/maps/2016/12/30/Standortverlauf_post">blogpost</a> from Shirin Glander was super useful and I am shamelessly stealing some of her brilliant ideas. The time stamp needs to be converted to be readable.
The field heading seems to be in degrees, is velocity in mph? And I don’t know where the altitude reading come from (maybe not a pressure sensor but gps triangulation?, ground elevation?).</p>
<pre class="r"><code>df &lt;- locations %&gt;% 
  mutate(datetime = as.POSIXct(as.numeric(timestampMs)/1000, origin = &quot;1970-01-01&quot;)) 

sort(unique(df$heading)) #naught to 360</code></pre>
<pre><code>##   [1]   0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16
##  [18]  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33
##  [35]  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50
##  [52]  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
##  [69]  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84
##  [86]  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
## [103] 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
## [120] 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
## [137] 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152
## [154] 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169
## [171] 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186
## [188] 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203
## [205] 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220
## [222] 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237
## [239] 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254
## [256] 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271
## [273] 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288
## [290] 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
## [307] 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322
## [324] 323 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339
## [341] 340 341 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356
## [358] 357 358 359</code></pre>
<p>Is the velocity in miles per hour ?</p>
<pre class="r"><code>unique(df$velocity)</code></pre>
<pre><code>##  [1] NA  0  1  3  5 14 28  2  4  7  8 25 29 15 16 19 10  6  9 11 13 12 21
## [24] 24 20 17 26 27 30 23 22 18 31 33 32 34 35 36 82 83 77 74 67 37</code></pre>
<p>Does that mean that I ever broke the speed limit? We’re not supposed to drive faster than 120 km/h in :BE: 😱</p>
<pre class="r"><code>#paste(round(max(unique(df$velocity), na.rm = TRUE)*1.609344,0),&quot;km!&quot;); ji(&quot;scream&quot;)
fine &lt;- paste(round(max(unique(df$velocity), na.rm = TRUE)*1.609344,0),&quot;km!&quot;)
scream &lt;- ji_glue(&quot;😱&quot;) 
glue(&quot;{fine} {scream} {scream} {scream}&quot;)</code></pre>
<pre><code>## 134 km! &lt;U+0001F631&gt; &lt;U+0001F631&gt; &lt;U+0001F631&gt;</code></pre>
<p>Could this information get me fined? Or will this type information be used in the future determine guilt?
Are the police allowed to access this type of Google data to for instance find perps of hit &amp; runs?</p>
<p>The data frame also contains lists with times stamps and estimations of activity at that time stamp.</p>
<pre class="r"><code>str(df$activity[80])</code></pre>
<pre><code>## List of 1
##  $ :&#39;data.frame&#39;:    1 obs. of  2 variables:
##   ..$ timestampMs: chr &quot;1395248054966&quot;
##   ..$ activity   :List of 1
##   .. ..$ :&#39;data.frame&#39;:  5 obs. of  2 variables:
##   .. .. ..$ type      : chr [1:5] &quot;ON_FOOT&quot; &quot;STILL&quot; &quot;IN_VEHICLE&quot; &quot;UNKNOWN&quot; ...
##   .. .. ..$ confidence: int [1:5] 49 20 16 10 2</code></pre>
<p>So if I read this correcttly this object is a list of one, containing a dataframe with another two objects, a timestamp and another list of one, that contains a dataframe with 5 observations and two variables, the type of activity and the probabilty calculated for it. So on timestamp “1395248054966” I had a 49% probablility to be on foot.</p>
<p>And then there is also a measure of altitude. Is it in feet or meters, and where do the negative numbers come from? Maybe these data points should be analysed a bit later.</p>
<pre class="r"><code>glimpse(unique(df$altitude)) # ? what sensor does it use?</code></pre>
<pre><code>##  int [1:633] NA 27 41 38 42 60 16 57 63 49 ...</code></pre>
<pre class="r"><code>summary(unique(df$altitude))</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
## -1299.0   108.8   266.5   274.0   435.2  2983.0       1</code></pre>
<p>Let’s plot some data on maps.</p>
<p>First some additional date prep.</p>
<pre class="r"><code>df &lt;- df %&gt;% 
  mutate(lat   = latitudeE7/1e7,
         lon   = longitudeE7/1e7,
         time  = strftime(datetime, format = &quot;%H:%M:%S&quot;),
         date  = date(datetime),
         year  = year(datetime),
         month = month(datetime),
         wday  = wday(datetime))</code></pre>
<p>Working with ggmap is pretty straightforward, but you need to obtain an api key from google and enable billing. More info <a href="https://developers.google.com/maps/documentation/embed/get-api-key">here</a>. For obvious reasons you need to keep your key secret and safe, but additionally you can restrict the calls to your <a href="https://console.developers.google.com/apis/credentials?project=grounded-block-178714&amp;folder&amp;organizationId">IP</a>. Will have a go at OSM in a future post, promised.</p>
<pre class="r"><code>secrets &lt;- readRDS(&quot;~/R/geo/secret/secrets.rds&quot;)
key &lt;- secrets$key[1]
register_google(key = key)

belgium &lt;- get_map(location = &#39;Belgium&#39;, zoom = 8, maptype = &quot;terrain-lines&quot;)</code></pre>
<p>The map coverage is called the bounding box of the map and it is an attribute of the ggmap object.</p>
<pre class="r"><code>bb &lt;- attr(belgium, &quot;bb&quot;)
bb</code></pre>
<pre><code>##          ll.lat  ll.lon ur.lat   ur.lon
## bottom 49.37082 2.71487 51.607 6.230495</code></pre>
<pre class="r"><code>x &lt;- df %&gt;% 
  filter(lat &lt; 51.607 &amp; lat &gt; 49.37082,
         lon &gt; 2.71487 &amp; lon &lt; 6.20495)</code></pre>
<pre class="r"><code>ggmap(belgium, maptype = &quot;terrain-lines&quot;) + 
  geom_point(data = x, aes(x = lon, y = lat),
             alpha = 0.1, color = &quot;#FC4E07&quot;, size = .65) + 
  theme(legend.position = &quot;right&quot;) + 
  labs(
    x = &quot;Longitude&quot;, 
    y = &quot;Latitude&quot;, 
    title = &quot;Location history data points in Belgium&quot;,
    caption = &quot;\nA simple point plot shows recorded positions.&quot;)</code></pre>
<p><img src="/post/2019-03-30-google-location-tracking_files/figure-html/unnamed-chunk-13-1.png" width="1440" /></p>
<p>Orange lines are my movements. A rock festival to the east of Antwerp, some visits to the coast, to my home city Ghent, a marriage in the west, biking and text mining in Leuven, and hikes in the woods of the south. Looks about right. And yes, I live and work in Brussels.</p>
<p>So let’s take a closer look at Brussels.</p>
<pre class="r"><code>Brussels &lt;- get_map(location = &#39;Brussels&#39;, zoom = 12, maptype = &quot;terrain-lines&quot;)</code></pre>
<pre><code>## maptype = &quot;terrain-lines&quot; is only available with source = &quot;stamen&quot;.</code></pre>
<pre><code>## resetting to source = &quot;stamen&quot;...</code></pre>
<pre><code>## Source : https://maps.googleapis.com/maps/api/staticmap?center=Brussels&amp;zoom=12&amp;size=640x640&amp;scale=2&amp;maptype=terrain&amp;key=xxx</code></pre>
<pre><code>## Source : https://maps.googleapis.com/maps/api/geocode/json?address=Brussels&amp;key=xxx</code></pre>
<pre><code>## Source : http://tile.stamen.com/terrain-lines/12/2096/1372.png</code></pre>
<pre><code>## Source : http://tile.stamen.com/terrain-lines/12/2097/1372.png</code></pre>
<pre><code>## Source : http://tile.stamen.com/terrain-lines/12/2098/1372.png</code></pre>
<pre><code>## Source : http://tile.stamen.com/terrain-lines/12/2096/1373.png</code></pre>
<pre><code>## Source : http://tile.stamen.com/terrain-lines/12/2097/1373.png</code></pre>
<pre><code>## Source : http://tile.stamen.com/terrain-lines/12/2098/1373.png</code></pre>
<pre><code>## Source : http://tile.stamen.com/terrain-lines/12/2096/1374.png</code></pre>
<pre><code>## Source : http://tile.stamen.com/terrain-lines/12/2097/1374.png</code></pre>
<pre><code>## Source : http://tile.stamen.com/terrain-lines/12/2098/1374.png</code></pre>
<pre><code>## Source : http://tile.stamen.com/terrain-lines/12/2096/1375.png</code></pre>
<pre><code>## Source : http://tile.stamen.com/terrain-lines/12/2097/1375.png</code></pre>
<pre><code>## Source : http://tile.stamen.com/terrain-lines/12/2098/1375.png</code></pre>
<pre class="r"><code>ggmap(Brussels) + 
  geom_point(data = x, aes(x = lon, y = lat),
             alpha = 0.5, color = &quot;#FC4E07&quot;, size = .65) + 
  theme(legend.position = &quot;right&quot;) + 
  labs(
    x = &quot;Longitude&quot;, 
    y = &quot;Latitude&quot;, 
    title = &quot;Location history data points in Brussels&quot;,
    caption = &quot;\nA simple point plot shows recorded positions.&quot;)</code></pre>
<pre><code>## Warning: Removed 42343 rows containing missing values (geom_point).</code></pre>
<p><img src="/post/2019-03-30-google-location-tracking_files/figure-html/unnamed-chunk-15-1.png" width="1440" /></p>

      
      <div class="related">
</div>
      
    </div>
    
  </div>
</section>


<section class="section">
  <div class="container">
    <aside><div id="disqus_thread"></div></aside>
  
    <div id="show_comments"><a id="load_comments" class="button is-link">Load comments</a></div>
  
    <script type="text/javascript">
      var disqus_shortname = 'shortname';
      function disqus() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      }
  
      
      var hash = window.location.hash.substr(1);
      if ((hash.length > 8) && (hash.substring(0, 8) === "comment-")) {
        disqus();
        document.getElementById("show_comments").style.display = "none";
      } else {
        document.getElementById('load_comments').onclick = function() {
          disqus();
          document.getElementById("show_comments").style.display = "none";
        };
      }
  

    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
  </div>
</section>


<section class="section">
  <div class="container has-text-centered">
    <p>&copy; <a href="https://github.com/madcap1090">William Bourgeois</a> 2019</p>
    
      <p>Powered by <a href="https://gohugo.io/">Hugo</a> &amp; <a href="https://github.com/ribice/kiss">Kiss</a>.</p>
    
  </div>
</section>


<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
	ga('create', 'UA-137981534-1', 'auto');
	
	ga('send', 'pageview');
}
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>


<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="\/\/matomo.example.com\/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript>
  <img src="//matomo.example.com/piwik.php?idsite=1&amp;rec=1" style="border:0" alt="" />
</noscript>


</body>
</html>

